import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Scale, CheckCircle2, AlertTriangle, Shield } from 'lucide-react';

export default function TermsOfService() {
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'instant' });
  }, []);

  return (
    <div className="relative pt-32 pb-24 bg-background min-h-[80vh] overflow-hidden">
      {/* Ambient background glow */}
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-96 h-96 rounded-full bg-white/5 blur-[120px] pointer-events-none z-0" />

      <div className="max-w-4xl mx-auto px-4 sm:px-6 relative z-10">
        {/* Back Button */}
        <Link 
          to="/" 
          className="inline-flex items-center gap-2 text-xs font-semibold text-lightGray/50 hover:text-white mb-8 group transition-colors focus:outline-none"
        >
          <ArrowLeft size={14} className="group-hover:-translate-x-0.5 transition-transform" />
          Back to Workspace Home
        </Link>

        {/* Hero title */}
        <div className="mb-12">
          <div className="flex items-center gap-2.5 mb-3">
            <Scale className="text-white" size={20} />
            <span className="text-[10px] font-bold text-white uppercase tracking-widest bg-white/5 border border-white/10 px-2.5 py-0.5 rounded-full">
              Legal Terms
            </span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-white mb-4">
            Terms of Service
          </h1>
          <p className="text-xs text-lightGray/40">
            Last Updated: July 1, 2026
          </p>
        </div>

        {/* Content Card */}
        <div className="glassmorphism premium-border p-8 sm:p-12 rounded-2xl space-y-10 text-sm text-lightGray/85 leading-relaxed">
          <section className="space-y-4">
            <h2 className="text-lg font-bold text-white flex items-center gap-2">
              <CheckCircle2 size={18} className="text-white/60" /> 1. Agreement to Terms
            </h2>
            <p>
              By accessing the website at `http://localhost:5173` or utilizing the InterviewAce.AI workspace portal, you agree to comply with and be bound by these Terms of Service. If you do not agree, you are prohibited from utilizing the simulation engines, compiler sandbox, and AI resume auditing systems.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-bold text-white flex items-center gap-2">
              <Shield size={18} className="text-white/60" /> 2. License and Acceptable Use
            </h2>
            <p>
              Candidates are granted a limited, personal, non-transferable license to access preparation tools. You agree not to:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-lightGray/70">
              <li>Reverse engineer or scrape mock question datasets generated by our AI modules.</li>
              <li>Exploit sandbox compilers or initiate DDoS events against remote compiling nodes.</li>
              <li>Deploy automated scripts or bots to consume sandbox limits artificially.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-bold text-white flex items-center gap-2">
              <AlertTriangle size={18} className="text-white/60" /> 3. Subscriptions and Limits
            </h2>
            <p>
              For public launch, users are assigned to the Premium plan with high limit configurations. We reserve the right to monitor account usage behavior and modify or restrict query rates if we detect anomalous usage patterns that threaten service stability.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-bold text-white">4. Disclaimers and Liabilities</h2>
            <p>
              InterviewAce.AI provides educational evaluations and interview simulation feedback. We do not guarantee placement outcomes, selection passes, or employment success at Google, TCS, Meta, or any specific employer. The services are provided "as-is" without warranty.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-bold text-white flex items-center gap-2">
              <Scale size={18} className="text-white/60" /> 5. Payments, Subscriptions, and Refunds
            </h2>
            <p>
              Upgrades to Premium or other paid assessments are processed securely via third-party payment gateways. All fees paid are non-refundable unless specified otherwise by local consumer protection statutes. If you encounter a billing discrepancy, contact support within 14 business days.
            </p>
          </section>

          <section className="space-y-4 pt-6 border-t border-white/5">
            <h3 className="text-sm font-bold text-white">Need Clarification?</h3>
            <p className="text-xs text-lightGray/60">
              If you have queries regarding user rules, subscription cancellations, or developer licenses, contact our operations desk at <a href="mailto:terms@interviewace.ai" className="text-white underline hover:text-lightGray transition-colors">terms@interviewace.ai</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
